#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysOtica
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SysOtica")]
	public partial class SysOticaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcategoria(categoria instance);
    partial void Updatecategoria(categoria instance);
    partial void Deletecategoria(categoria instance);
    partial void InsertVenda(Venda instance);
    partial void UpdateVenda(Venda instance);
    partial void DeleteVenda(Venda instance);
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    partial void Insertfornecedor(fornecedor instance);
    partial void Updatefornecedor(fornecedor instance);
    partial void Deletefornecedor(fornecedor instance);
    partial void InsertItemVenda(ItemVenda instance);
    partial void UpdateItemVenda(ItemVenda instance);
    partial void DeleteItemVenda(ItemVenda instance);
    partial void Insertproduto(produto instance);
    partial void Updateproduto(produto instance);
    partial void Deleteproduto(produto instance);
    partial void Insertprodutofornecedor(produtofornecedor instance);
    partial void Updateprodutofornecedor(produtofornecedor instance);
    partial void Deleteprodutofornecedor(produtofornecedor instance);
    partial void Insertprodutovenda(produtovenda instance);
    partial void Updateprodutovenda(produtovenda instance);
    partial void Deleteprodutovenda(produtovenda instance);
    partial void Insertreceita(receita instance);
    partial void Updatereceita(receita instance);
    partial void Deletereceita(receita instance);
    #endregion
		
		public SysOticaDBDataContext() : 
				base(global::SysOtica.Properties.Settings.Default.SysOticaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public SysOticaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SysOticaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SysOticaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SysOticaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<categoria> categorias
		{
			get
			{
				return this.GetTable<categoria>();
			}
		}
		
		public System.Data.Linq.Table<Venda> Vendas
		{
			get
			{
				return this.GetTable<Venda>();
			}
		}
		
		public System.Data.Linq.Table<cliente> clientes
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<fornecedor> fornecedors
		{
			get
			{
				return this.GetTable<fornecedor>();
			}
		}
		
		public System.Data.Linq.Table<ItemVenda> ItemVendas
		{
			get
			{
				return this.GetTable<ItemVenda>();
			}
		}
		
		public System.Data.Linq.Table<produto> produtos
		{
			get
			{
				return this.GetTable<produto>();
			}
		}
		
		public System.Data.Linq.Table<produtofornecedor> produtofornecedors
		{
			get
			{
				return this.GetTable<produtofornecedor>();
			}
		}
		
		public System.Data.Linq.Table<produtovenda> produtovendas
		{
			get
			{
				return this.GetTable<produtovenda>();
			}
		}
		
		public System.Data.Linq.Table<receita> receitas
		{
			get
			{
				return this.GetTable<receita>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categoria")]
	public partial class categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ct_id;
		
		private string _ct_nome;
		
		private EntitySet<produto> _produtos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onct_idChanging(int value);
    partial void Onct_idChanged();
    partial void Onct_nomeChanging(string value);
    partial void Onct_nomeChanged();
    #endregion
		
		public categoria()
		{
			this._produtos = new EntitySet<produto>(new Action<produto>(this.attach_produtos), new Action<produto>(this.detach_produtos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ct_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ct_id
		{
			get
			{
				return this._ct_id;
			}
			set
			{
				if ((this._ct_id != value))
				{
					this.Onct_idChanging(value);
					this.SendPropertyChanging();
					this._ct_id = value;
					this.SendPropertyChanged("ct_id");
					this.Onct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ct_nome", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ct_nome
		{
			get
			{
				return this._ct_nome;
			}
			set
			{
				if ((this._ct_nome != value))
				{
					this.Onct_nomeChanging(value);
					this.SendPropertyChanging();
					this._ct_nome = value;
					this.SendPropertyChanged("ct_nome");
					this.Onct_nomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_produto", Storage="_produtos", ThisKey="ct_id", OtherKey="ct_id")]
		public EntitySet<produto> produtos
		{
			get
			{
				return this._produtos;
			}
			set
			{
				this._produtos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_produtos(produto entity)
		{
			this.SendPropertyChanging();
			entity.categoria = this;
		}
		
		private void detach_produtos(produto entity)
		{
			this.SendPropertyChanging();
			entity.categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.venda")]
	public partial class Venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoVenda;
		
		private int _CodigoCliente;
		
		private System.Nullable<decimal> _Valor;
		
		private System.Nullable<decimal> _ValorPago;
		
		private System.Nullable<decimal> _Desconto;
		
		private string _FormaPagamento;
		
		private EntitySet<ItemVenda> _itensVendas;
		
		private EntitySet<ItemVenda> _ItemVendas;
		
		private EntitySet<produtovenda> _produtovendas;
		
		private EntityRef<cliente> _cliente;
		
		private EntityRef<cliente> _cliente1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoVendaChanging(int value);
    partial void OnCodigoVendaChanged();
    partial void OnCodigoClienteChanging(int value);
    partial void OnCodigoClienteChanged();
    partial void OnValorChanging(System.Nullable<decimal> value);
    partial void OnValorChanged();
    partial void OnValorPagoChanging(System.Nullable<decimal> value);
    partial void OnValorPagoChanged();
    partial void OnDescontoChanging(System.Nullable<decimal> value);
    partial void OnDescontoChanged();
    partial void OnFormaPagamentoChanging(string value);
    partial void OnFormaPagamentoChanged();
    #endregion
		
		public Venda()
		{
			this._itensVendas = new EntitySet<ItemVenda>(new Action<ItemVenda>(this.attach_itensVendas), new Action<ItemVenda>(this.detach_itensVendas));
			this._ItemVendas = new EntitySet<ItemVenda>(new Action<ItemVenda>(this.attach_ItemVendas), new Action<ItemVenda>(this.detach_ItemVendas));
			this._produtovendas = new EntitySet<produtovenda>(new Action<produtovenda>(this.attach_produtovendas), new Action<produtovenda>(this.detach_produtovendas));
			this._cliente = default(EntityRef<cliente>);
			this._cliente1 = default(EntityRef<cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Vn_id", Storage="_CodigoVenda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoVenda
		{
			get
			{
				return this._CodigoVenda;
			}
			set
			{
				if ((this._CodigoVenda != value))
				{
					this.OnCodigoVendaChanging(value);
					this.SendPropertyChanging();
					this._CodigoVenda = value;
					this.SendPropertyChanged("CodigoVenda");
					this.OnCodigoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cl_id", Storage="_CodigoCliente", DbType="Int NOT NULL")]
		public int CodigoCliente
		{
			get
			{
				return this._CodigoCliente;
			}
			set
			{
				if ((this._CodigoCliente != value))
				{
					this.OnCodigoClienteChanging(value);
					this.SendPropertyChanging();
					this._CodigoCliente = value;
					this.SendPropertyChanged("CodigoCliente");
					this.OnCodigoClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Vn_valor", Storage="_Valor", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Vn_valortotal", Storage="_ValorPago", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> ValorPago
		{
			get
			{
				return this._ValorPago;
			}
			set
			{
				if ((this._ValorPago != value))
				{
					this.OnValorPagoChanging(value);
					this.SendPropertyChanging();
					this._ValorPago = value;
					this.SendPropertyChanged("ValorPago");
					this.OnValorPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Vn_desconto", Storage="_Desconto", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Desconto
		{
			get
			{
				return this._Desconto;
			}
			set
			{
				if ((this._Desconto != value))
				{
					this.OnDescontoChanging(value);
					this.SendPropertyChanging();
					this._Desconto = value;
					this.SendPropertyChanged("Desconto");
					this.OnDescontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Vn_formapagamento", Storage="_FormaPagamento", DbType="VarChar(20)")]
		public string FormaPagamento
		{
			get
			{
				return this._FormaPagamento;
			}
			set
			{
				if ((this._FormaPagamento != value))
				{
					this.OnFormaPagamentoChanging(value);
					this.SendPropertyChanging();
					this._FormaPagamento = value;
					this.SendPropertyChanged("FormaPagamento");
					this.OnFormaPagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="venda_itensVenda", Storage="_itensVendas", ThisKey="CodigoVenda", OtherKey="CodigoVenda")]
		public EntitySet<ItemVenda> itensVendas
		{
			get
			{
				return this._itensVendas;
			}
			set
			{
				this._itensVendas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="venda_itensVenda1", Storage="_ItemVendas", ThisKey="CodigoVenda", OtherKey="CodigoVenda")]
		public EntitySet<ItemVenda> ItemVendas
		{
			get
			{
				return this._ItemVendas;
			}
			set
			{
				this._ItemVendas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="venda_produtovenda", Storage="_produtovendas", ThisKey="CodigoVenda", OtherKey="Vn_id")]
		public EntitySet<produtovenda> produtovendas
		{
			get
			{
				return this._produtovendas;
			}
			set
			{
				this._produtovendas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_venda", Storage="_cliente", ThisKey="CodigoCliente", OtherKey="cl_id", IsForeignKey=true)]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.vendas.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.vendas.Add(this);
						this._CodigoCliente = value.cl_id;
					}
					else
					{
						this._CodigoCliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_venda1", Storage="_cliente1", ThisKey="CodigoCliente", OtherKey="cl_id", IsForeignKey=true)]
		public cliente cliente1
		{
			get
			{
				return this._cliente1.Entity;
			}
			set
			{
				cliente previousValue = this._cliente1.Entity;
				if (((previousValue != value) 
							|| (this._cliente1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente1.Entity = null;
						previousValue.Vendas1.Remove(this);
					}
					this._cliente1.Entity = value;
					if ((value != null))
					{
						value.Vendas1.Add(this);
						this._CodigoCliente = value.cl_id;
					}
					else
					{
						this._CodigoCliente = default(int);
					}
					this.SendPropertyChanged("cliente1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_itensVendas(ItemVenda entity)
		{
			this.SendPropertyChanging();
			entity.venda = this;
		}
		
		private void detach_itensVendas(ItemVenda entity)
		{
			this.SendPropertyChanging();
			entity.venda = null;
		}
		
		private void attach_ItemVendas(ItemVenda entity)
		{
			this.SendPropertyChanging();
			entity.Venda1 = this;
		}
		
		private void detach_ItemVendas(ItemVenda entity)
		{
			this.SendPropertyChanging();
			entity.Venda1 = null;
		}
		
		private void attach_produtovendas(produtovenda entity)
		{
			this.SendPropertyChanging();
			entity.Venda = this;
		}
		
		private void detach_produtovendas(produtovenda entity)
		{
			this.SendPropertyChanging();
			entity.Venda = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cl_id;
		
		private string _cl_nome;
		
		private System.DateTime _cl_datanascimento;
		
		private string _cl_cpf;
		
		private string _cl_rg;
		
		private string _cl_telefone;
		
		private string _cl_celular;
		
		private string _cl_telefone2;
		
		private string _cl_cep;
		
		private string _cl_endereco;
		
		private string _cl_numero;
		
		private string _cl_bairro;
		
		private string _cl_cidade;
		
		private string _cl_uf;
		
		private string _cl_email;
		
		private string _cl_nomepai;
		
		private string _cl_nomemae;
		
		private string _cl_profissao;
		
		private string _cl_observacoes;
		
		private EntitySet<Venda> _vendas;
		
		private EntitySet<Venda> _Vendas1;
		
		private EntitySet<receita> _receitas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncl_idChanging(int value);
    partial void Oncl_idChanged();
    partial void Oncl_nomeChanging(string value);
    partial void Oncl_nomeChanged();
    partial void Oncl_datanascimentoChanging(System.DateTime value);
    partial void Oncl_datanascimentoChanged();
    partial void Oncl_cpfChanging(string value);
    partial void Oncl_cpfChanged();
    partial void Oncl_rgChanging(string value);
    partial void Oncl_rgChanged();
    partial void Oncl_telefoneChanging(string value);
    partial void Oncl_telefoneChanged();
    partial void Oncl_celularChanging(string value);
    partial void Oncl_celularChanged();
    partial void Oncl_telefone2Changing(string value);
    partial void Oncl_telefone2Changed();
    partial void Oncl_cepChanging(string value);
    partial void Oncl_cepChanged();
    partial void Oncl_enderecoChanging(string value);
    partial void Oncl_enderecoChanged();
    partial void Oncl_numeroChanging(string value);
    partial void Oncl_numeroChanged();
    partial void Oncl_bairroChanging(string value);
    partial void Oncl_bairroChanged();
    partial void Oncl_cidadeChanging(string value);
    partial void Oncl_cidadeChanged();
    partial void Oncl_ufChanging(string value);
    partial void Oncl_ufChanged();
    partial void Oncl_emailChanging(string value);
    partial void Oncl_emailChanged();
    partial void Oncl_nomepaiChanging(string value);
    partial void Oncl_nomepaiChanged();
    partial void Oncl_nomemaeChanging(string value);
    partial void Oncl_nomemaeChanged();
    partial void Oncl_profissaoChanging(string value);
    partial void Oncl_profissaoChanged();
    partial void Oncl_observacoesChanging(string value);
    partial void Oncl_observacoesChanged();
    #endregion
		
		public cliente()
		{
			this._vendas = new EntitySet<Venda>(new Action<Venda>(this.attach_vendas), new Action<Venda>(this.detach_vendas));
			this._Vendas1 = new EntitySet<Venda>(new Action<Venda>(this.attach_Vendas1), new Action<Venda>(this.detach_Vendas1));
			this._receitas = new EntitySet<receita>(new Action<receita>(this.attach_receitas), new Action<receita>(this.detach_receitas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cl_id
		{
			get
			{
				return this._cl_id;
			}
			set
			{
				if ((this._cl_id != value))
				{
					this.Oncl_idChanging(value);
					this.SendPropertyChanging();
					this._cl_id = value;
					this.SendPropertyChanged("cl_id");
					this.Oncl_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string cl_nome
		{
			get
			{
				return this._cl_nome;
			}
			set
			{
				if ((this._cl_nome != value))
				{
					this.Oncl_nomeChanging(value);
					this.SendPropertyChanging();
					this._cl_nome = value;
					this.SendPropertyChanged("cl_nome");
					this.Oncl_nomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_datanascimento", DbType="Date NOT NULL")]
		public System.DateTime cl_datanascimento
		{
			get
			{
				return this._cl_datanascimento;
			}
			set
			{
				if ((this._cl_datanascimento != value))
				{
					this.Oncl_datanascimentoChanging(value);
					this.SendPropertyChanging();
					this._cl_datanascimento = value;
					this.SendPropertyChanged("cl_datanascimento");
					this.Oncl_datanascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_cpf", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cl_cpf
		{
			get
			{
				return this._cl_cpf;
			}
			set
			{
				if ((this._cl_cpf != value))
				{
					this.Oncl_cpfChanging(value);
					this.SendPropertyChanging();
					this._cl_cpf = value;
					this.SendPropertyChanged("cl_cpf");
					this.Oncl_cpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_rg", DbType="VarChar(20)")]
		public string cl_rg
		{
			get
			{
				return this._cl_rg;
			}
			set
			{
				if ((this._cl_rg != value))
				{
					this.Oncl_rgChanging(value);
					this.SendPropertyChanging();
					this._cl_rg = value;
					this.SendPropertyChanged("cl_rg");
					this.Oncl_rgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_telefone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cl_telefone
		{
			get
			{
				return this._cl_telefone;
			}
			set
			{
				if ((this._cl_telefone != value))
				{
					this.Oncl_telefoneChanging(value);
					this.SendPropertyChanging();
					this._cl_telefone = value;
					this.SendPropertyChanged("cl_telefone");
					this.Oncl_telefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_celular", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cl_celular
		{
			get
			{
				return this._cl_celular;
			}
			set
			{
				if ((this._cl_celular != value))
				{
					this.Oncl_celularChanging(value);
					this.SendPropertyChanging();
					this._cl_celular = value;
					this.SendPropertyChanged("cl_celular");
					this.Oncl_celularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_telefone2", DbType="VarChar(20)")]
		public string cl_telefone2
		{
			get
			{
				return this._cl_telefone2;
			}
			set
			{
				if ((this._cl_telefone2 != value))
				{
					this.Oncl_telefone2Changing(value);
					this.SendPropertyChanging();
					this._cl_telefone2 = value;
					this.SendPropertyChanged("cl_telefone2");
					this.Oncl_telefone2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_cep", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cl_cep
		{
			get
			{
				return this._cl_cep;
			}
			set
			{
				if ((this._cl_cep != value))
				{
					this.Oncl_cepChanging(value);
					this.SendPropertyChanging();
					this._cl_cep = value;
					this.SendPropertyChanged("cl_cep");
					this.Oncl_cepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_endereco", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string cl_endereco
		{
			get
			{
				return this._cl_endereco;
			}
			set
			{
				if ((this._cl_endereco != value))
				{
					this.Oncl_enderecoChanging(value);
					this.SendPropertyChanging();
					this._cl_endereco = value;
					this.SendPropertyChanged("cl_endereco");
					this.Oncl_enderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_numero", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string cl_numero
		{
			get
			{
				return this._cl_numero;
			}
			set
			{
				if ((this._cl_numero != value))
				{
					this.Oncl_numeroChanging(value);
					this.SendPropertyChanging();
					this._cl_numero = value;
					this.SendPropertyChanged("cl_numero");
					this.Oncl_numeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_bairro", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cl_bairro
		{
			get
			{
				return this._cl_bairro;
			}
			set
			{
				if ((this._cl_bairro != value))
				{
					this.Oncl_bairroChanging(value);
					this.SendPropertyChanging();
					this._cl_bairro = value;
					this.SendPropertyChanged("cl_bairro");
					this.Oncl_bairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_cidade", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cl_cidade
		{
			get
			{
				return this._cl_cidade;
			}
			set
			{
				if ((this._cl_cidade != value))
				{
					this.Oncl_cidadeChanging(value);
					this.SendPropertyChanging();
					this._cl_cidade = value;
					this.SendPropertyChanged("cl_cidade");
					this.Oncl_cidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_uf", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string cl_uf
		{
			get
			{
				return this._cl_uf;
			}
			set
			{
				if ((this._cl_uf != value))
				{
					this.Oncl_ufChanging(value);
					this.SendPropertyChanging();
					this._cl_uf = value;
					this.SendPropertyChanged("cl_uf");
					this.Oncl_ufChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_email", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string cl_email
		{
			get
			{
				return this._cl_email;
			}
			set
			{
				if ((this._cl_email != value))
				{
					this.Oncl_emailChanging(value);
					this.SendPropertyChanging();
					this._cl_email = value;
					this.SendPropertyChanged("cl_email");
					this.Oncl_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_nomepai", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string cl_nomepai
		{
			get
			{
				return this._cl_nomepai;
			}
			set
			{
				if ((this._cl_nomepai != value))
				{
					this.Oncl_nomepaiChanging(value);
					this.SendPropertyChanging();
					this._cl_nomepai = value;
					this.SendPropertyChanged("cl_nomepai");
					this.Oncl_nomepaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_nomemae", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string cl_nomemae
		{
			get
			{
				return this._cl_nomemae;
			}
			set
			{
				if ((this._cl_nomemae != value))
				{
					this.Oncl_nomemaeChanging(value);
					this.SendPropertyChanging();
					this._cl_nomemae = value;
					this.SendPropertyChanged("cl_nomemae");
					this.Oncl_nomemaeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_profissao", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cl_profissao
		{
			get
			{
				return this._cl_profissao;
			}
			set
			{
				if ((this._cl_profissao != value))
				{
					this.Oncl_profissaoChanging(value);
					this.SendPropertyChanging();
					this._cl_profissao = value;
					this.SendPropertyChanged("cl_profissao");
					this.Oncl_profissaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_observacoes", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string cl_observacoes
		{
			get
			{
				return this._cl_observacoes;
			}
			set
			{
				if ((this._cl_observacoes != value))
				{
					this.Oncl_observacoesChanging(value);
					this.SendPropertyChanging();
					this._cl_observacoes = value;
					this.SendPropertyChanged("cl_observacoes");
					this.Oncl_observacoesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_venda", Storage="_vendas", ThisKey="cl_id", OtherKey="CodigoCliente")]
		public EntitySet<Venda> vendas
		{
			get
			{
				return this._vendas;
			}
			set
			{
				this._vendas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_venda1", Storage="_Vendas1", ThisKey="cl_id", OtherKey="CodigoCliente")]
		public EntitySet<Venda> Vendas1
		{
			get
			{
				return this._Vendas1;
			}
			set
			{
				this._Vendas1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_receita", Storage="_receitas", ThisKey="cl_id", OtherKey="cl_id")]
		public EntitySet<receita> receitas
		{
			get
			{
				return this._receitas;
			}
			set
			{
				this._receitas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_vendas(Venda entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_vendas(Venda entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
		
		private void attach_Vendas1(Venda entity)
		{
			this.SendPropertyChanging();
			entity.cliente1 = this;
		}
		
		private void detach_Vendas1(Venda entity)
		{
			this.SendPropertyChanging();
			entity.cliente1 = null;
		}
		
		private void attach_receitas(receita entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_receitas(receita entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fornecedor")]
	public partial class fornecedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fr_id;
		
		private string _fr_razaosocial;
		
		private string _fr_inscricaoestadual;
		
		private string _fr_fantasia;
		
		private string _fr_endereco;
		
		private string _fr_cidade;
		
		private string _fr_uf;
		
		private string _fr_bairro;
		
		private string _fr_cep;
		
		private string _fr_contato;
		
		private string _fr_telefone;
		
		private string _fr_fax;
		
		private string _fr_email;
		
		private string _fr_nomerepresentante;
		
		private string _fr_telefonerepresentante;
		
		private string _fr_celularrepresentante;
		
		private string _fr_observacoes;
		
		private string _fr_cnpj;
		
		private EntitySet<produtofornecedor> _produtofornecedors;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfr_idChanging(int value);
    partial void Onfr_idChanged();
    partial void Onfr_razaosocialChanging(string value);
    partial void Onfr_razaosocialChanged();
    partial void Onfr_inscricaoestadualChanging(string value);
    partial void Onfr_inscricaoestadualChanged();
    partial void Onfr_fantasiaChanging(string value);
    partial void Onfr_fantasiaChanged();
    partial void Onfr_enderecoChanging(string value);
    partial void Onfr_enderecoChanged();
    partial void Onfr_cidadeChanging(string value);
    partial void Onfr_cidadeChanged();
    partial void Onfr_ufChanging(string value);
    partial void Onfr_ufChanged();
    partial void Onfr_bairroChanging(string value);
    partial void Onfr_bairroChanged();
    partial void Onfr_cepChanging(string value);
    partial void Onfr_cepChanged();
    partial void Onfr_contatoChanging(string value);
    partial void Onfr_contatoChanged();
    partial void Onfr_telefoneChanging(string value);
    partial void Onfr_telefoneChanged();
    partial void Onfr_faxChanging(string value);
    partial void Onfr_faxChanged();
    partial void Onfr_emailChanging(string value);
    partial void Onfr_emailChanged();
    partial void Onfr_nomerepresentanteChanging(string value);
    partial void Onfr_nomerepresentanteChanged();
    partial void Onfr_telefonerepresentanteChanging(string value);
    partial void Onfr_telefonerepresentanteChanged();
    partial void Onfr_celularrepresentanteChanging(string value);
    partial void Onfr_celularrepresentanteChanged();
    partial void Onfr_observacoesChanging(string value);
    partial void Onfr_observacoesChanged();
    partial void Onfr_cnpjChanging(string value);
    partial void Onfr_cnpjChanged();
    #endregion
		
		public fornecedor()
		{
			this._produtofornecedors = new EntitySet<produtofornecedor>(new Action<produtofornecedor>(this.attach_produtofornecedors), new Action<produtofornecedor>(this.detach_produtofornecedors));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fr_id
		{
			get
			{
				return this._fr_id;
			}
			set
			{
				if ((this._fr_id != value))
				{
					this.Onfr_idChanging(value);
					this.SendPropertyChanging();
					this._fr_id = value;
					this.SendPropertyChanged("fr_id");
					this.Onfr_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_razaosocial", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string fr_razaosocial
		{
			get
			{
				return this._fr_razaosocial;
			}
			set
			{
				if ((this._fr_razaosocial != value))
				{
					this.Onfr_razaosocialChanging(value);
					this.SendPropertyChanging();
					this._fr_razaosocial = value;
					this.SendPropertyChanged("fr_razaosocial");
					this.Onfr_razaosocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_inscricaoestadual", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fr_inscricaoestadual
		{
			get
			{
				return this._fr_inscricaoestadual;
			}
			set
			{
				if ((this._fr_inscricaoestadual != value))
				{
					this.Onfr_inscricaoestadualChanging(value);
					this.SendPropertyChanging();
					this._fr_inscricaoestadual = value;
					this.SendPropertyChanged("fr_inscricaoestadual");
					this.Onfr_inscricaoestadualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_fantasia", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fr_fantasia
		{
			get
			{
				return this._fr_fantasia;
			}
			set
			{
				if ((this._fr_fantasia != value))
				{
					this.Onfr_fantasiaChanging(value);
					this.SendPropertyChanging();
					this._fr_fantasia = value;
					this.SendPropertyChanged("fr_fantasia");
					this.Onfr_fantasiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_endereco", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string fr_endereco
		{
			get
			{
				return this._fr_endereco;
			}
			set
			{
				if ((this._fr_endereco != value))
				{
					this.Onfr_enderecoChanging(value);
					this.SendPropertyChanging();
					this._fr_endereco = value;
					this.SendPropertyChanged("fr_endereco");
					this.Onfr_enderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_cidade", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fr_cidade
		{
			get
			{
				return this._fr_cidade;
			}
			set
			{
				if ((this._fr_cidade != value))
				{
					this.Onfr_cidadeChanging(value);
					this.SendPropertyChanging();
					this._fr_cidade = value;
					this.SendPropertyChanged("fr_cidade");
					this.Onfr_cidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_uf", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string fr_uf
		{
			get
			{
				return this._fr_uf;
			}
			set
			{
				if ((this._fr_uf != value))
				{
					this.Onfr_ufChanging(value);
					this.SendPropertyChanging();
					this._fr_uf = value;
					this.SendPropertyChanged("fr_uf");
					this.Onfr_ufChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_bairro", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string fr_bairro
		{
			get
			{
				return this._fr_bairro;
			}
			set
			{
				if ((this._fr_bairro != value))
				{
					this.Onfr_bairroChanging(value);
					this.SendPropertyChanging();
					this._fr_bairro = value;
					this.SendPropertyChanged("fr_bairro");
					this.Onfr_bairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_cep", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string fr_cep
		{
			get
			{
				return this._fr_cep;
			}
			set
			{
				if ((this._fr_cep != value))
				{
					this.Onfr_cepChanging(value);
					this.SendPropertyChanging();
					this._fr_cep = value;
					this.SendPropertyChanged("fr_cep");
					this.Onfr_cepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_contato", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string fr_contato
		{
			get
			{
				return this._fr_contato;
			}
			set
			{
				if ((this._fr_contato != value))
				{
					this.Onfr_contatoChanging(value);
					this.SendPropertyChanging();
					this._fr_contato = value;
					this.SendPropertyChanged("fr_contato");
					this.Onfr_contatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_telefone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string fr_telefone
		{
			get
			{
				return this._fr_telefone;
			}
			set
			{
				if ((this._fr_telefone != value))
				{
					this.Onfr_telefoneChanging(value);
					this.SendPropertyChanging();
					this._fr_telefone = value;
					this.SendPropertyChanged("fr_telefone");
					this.Onfr_telefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_fax", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string fr_fax
		{
			get
			{
				return this._fr_fax;
			}
			set
			{
				if ((this._fr_fax != value))
				{
					this.Onfr_faxChanging(value);
					this.SendPropertyChanging();
					this._fr_fax = value;
					this.SendPropertyChanged("fr_fax");
					this.Onfr_faxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fr_email
		{
			get
			{
				return this._fr_email;
			}
			set
			{
				if ((this._fr_email != value))
				{
					this.Onfr_emailChanging(value);
					this.SendPropertyChanging();
					this._fr_email = value;
					this.SendPropertyChanged("fr_email");
					this.Onfr_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_nomerepresentante", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fr_nomerepresentante
		{
			get
			{
				return this._fr_nomerepresentante;
			}
			set
			{
				if ((this._fr_nomerepresentante != value))
				{
					this.Onfr_nomerepresentanteChanging(value);
					this.SendPropertyChanging();
					this._fr_nomerepresentante = value;
					this.SendPropertyChanged("fr_nomerepresentante");
					this.Onfr_nomerepresentanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_telefonerepresentante", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string fr_telefonerepresentante
		{
			get
			{
				return this._fr_telefonerepresentante;
			}
			set
			{
				if ((this._fr_telefonerepresentante != value))
				{
					this.Onfr_telefonerepresentanteChanging(value);
					this.SendPropertyChanging();
					this._fr_telefonerepresentante = value;
					this.SendPropertyChanged("fr_telefonerepresentante");
					this.Onfr_telefonerepresentanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_celularrepresentante", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string fr_celularrepresentante
		{
			get
			{
				return this._fr_celularrepresentante;
			}
			set
			{
				if ((this._fr_celularrepresentante != value))
				{
					this.Onfr_celularrepresentanteChanging(value);
					this.SendPropertyChanging();
					this._fr_celularrepresentante = value;
					this.SendPropertyChanged("fr_celularrepresentante");
					this.Onfr_celularrepresentanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_observacoes", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string fr_observacoes
		{
			get
			{
				return this._fr_observacoes;
			}
			set
			{
				if ((this._fr_observacoes != value))
				{
					this.Onfr_observacoesChanging(value);
					this.SendPropertyChanging();
					this._fr_observacoes = value;
					this.SendPropertyChanged("fr_observacoes");
					this.Onfr_observacoesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_cnpj", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string fr_cnpj
		{
			get
			{
				return this._fr_cnpj;
			}
			set
			{
				if ((this._fr_cnpj != value))
				{
					this.Onfr_cnpjChanging(value);
					this.SendPropertyChanging();
					this._fr_cnpj = value;
					this.SendPropertyChanged("fr_cnpj");
					this.Onfr_cnpjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fornecedor_produtofornecedor", Storage="_produtofornecedors", ThisKey="fr_id", OtherKey="fr_id")]
		public EntitySet<produtofornecedor> produtofornecedors
		{
			get
			{
				return this._produtofornecedors;
			}
			set
			{
				this._produtofornecedors.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_produtofornecedors(produtofornecedor entity)
		{
			this.SendPropertyChanging();
			entity.fornecedor = this;
		}
		
		private void detach_produtofornecedors(produtofornecedor entity)
		{
			this.SendPropertyChanging();
			entity.fornecedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.itensVenda")]
	public partial class ItemVenda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Quantidade;
		
		private int _CodigoProduto;
		
		private int _CodigoVenda;
		
		private decimal _Valor;
		
		private int _CodigoItem;
		
		private EntityRef<Venda> _venda;
		
		private EntityRef<Venda> _Venda1;
		
		private EntityRef<produto> _produto;
		
		private EntityRef<produto> _produto1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuantidadeChanging(int value);
    partial void OnQuantidadeChanged();
    partial void OnCodigoProdutoChanging(int value);
    partial void OnCodigoProdutoChanged();
    partial void OnCodigoVendaChanging(int value);
    partial void OnCodigoVendaChanged();
    partial void OnValorChanging(decimal value);
    partial void OnValorChanged();
    partial void OnCodigoItemChanging(int value);
    partial void OnCodigoItemChanged();
    #endregion
		
		public ItemVenda()
		{
			this._venda = default(EntityRef<Venda>);
			this._Venda1 = default(EntityRef<Venda>);
			this._produto = default(EntityRef<produto>);
			this._produto1 = default(EntityRef<produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="iv_quantidade", Storage="_Quantidade", DbType="Int NOT NULL")]
		public int Quantidade
		{
			get
			{
				return this._Quantidade;
			}
			set
			{
				if ((this._Quantidade != value))
				{
					this.OnQuantidadeChanging(value);
					this.SendPropertyChanging();
					this._Quantidade = value;
					this.SendPropertyChanged("Quantidade");
					this.OnQuantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="pr_id", Storage="_CodigoProduto", DbType="Int NOT NULL")]
		public int CodigoProduto
		{
			get
			{
				return this._CodigoProduto;
			}
			set
			{
				if ((this._CodigoProduto != value))
				{
					this.OnCodigoProdutoChanging(value);
					this.SendPropertyChanging();
					this._CodigoProduto = value;
					this.SendPropertyChanged("CodigoProduto");
					this.OnCodigoProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Vn_id", Storage="_CodigoVenda", DbType="Int NOT NULL")]
		public int CodigoVenda
		{
			get
			{
				return this._CodigoVenda;
			}
			set
			{
				if ((this._CodigoVenda != value))
				{
					this.OnCodigoVendaChanging(value);
					this.SendPropertyChanging();
					this._CodigoVenda = value;
					this.SendPropertyChanged("CodigoVenda");
					this.OnCodigoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="iv_valor", Storage="_Valor", DbType="Decimal(15,2) NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="iv_id", Storage="_CodigoItem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoItem
		{
			get
			{
				return this._CodigoItem;
			}
			set
			{
				if ((this._CodigoItem != value))
				{
					this.OnCodigoItemChanging(value);
					this.SendPropertyChanging();
					this._CodigoItem = value;
					this.SendPropertyChanged("CodigoItem");
					this.OnCodigoItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="venda_itensVenda", Storage="_venda", ThisKey="CodigoVenda", OtherKey="CodigoVenda", IsForeignKey=true)]
		public Venda venda
		{
			get
			{
				return this._venda.Entity;
			}
			set
			{
				Venda previousValue = this._venda.Entity;
				if (((previousValue != value) 
							|| (this._venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._venda.Entity = null;
						previousValue.itensVendas.Remove(this);
					}
					this._venda.Entity = value;
					if ((value != null))
					{
						value.itensVendas.Add(this);
						this._CodigoVenda = value.CodigoVenda;
					}
					else
					{
						this._CodigoVenda = default(int);
					}
					this.SendPropertyChanged("venda");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="venda_itensVenda1", Storage="_Venda1", ThisKey="CodigoVenda", OtherKey="CodigoVenda", IsForeignKey=true)]
		public Venda Venda1
		{
			get
			{
				return this._Venda1.Entity;
			}
			set
			{
				Venda previousValue = this._Venda1.Entity;
				if (((previousValue != value) 
							|| (this._Venda1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Venda1.Entity = null;
						previousValue.ItemVendas.Remove(this);
					}
					this._Venda1.Entity = value;
					if ((value != null))
					{
						value.ItemVendas.Add(this);
						this._CodigoVenda = value.CodigoVenda;
					}
					else
					{
						this._CodigoVenda = default(int);
					}
					this.SendPropertyChanged("Venda1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produto_itensVenda", Storage="_produto", ThisKey="CodigoProduto", OtherKey="pr_id", IsForeignKey=true)]
		public produto produto
		{
			get
			{
				return this._produto.Entity;
			}
			set
			{
				produto previousValue = this._produto.Entity;
				if (((previousValue != value) 
							|| (this._produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._produto.Entity = null;
						previousValue.itensVendas.Remove(this);
					}
					this._produto.Entity = value;
					if ((value != null))
					{
						value.itensVendas.Add(this);
						this._CodigoProduto = value.pr_id;
					}
					else
					{
						this._CodigoProduto = default(int);
					}
					this.SendPropertyChanged("produto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produto_itensVenda1", Storage="_produto1", ThisKey="CodigoProduto", OtherKey="pr_id", IsForeignKey=true)]
		public produto produto1
		{
			get
			{
				return this._produto1.Entity;
			}
			set
			{
				produto previousValue = this._produto1.Entity;
				if (((previousValue != value) 
							|| (this._produto1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._produto1.Entity = null;
						previousValue.ItemVendas.Remove(this);
					}
					this._produto1.Entity = value;
					if ((value != null))
					{
						value.ItemVendas.Add(this);
						this._CodigoProduto = value.pr_id;
					}
					else
					{
						this._CodigoProduto = default(int);
					}
					this.SendPropertyChanged("produto1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.produto")]
	public partial class produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pr_id;
		
		private int _ct_id;
		
		private string _pr_descricao;
		
		private string _pr_unidade;
		
		private string _pr_grife;
		
		private decimal _pr_valor;
		
		private int _pr_estoqueminimo;
		
		private string _pr_categoria;
		
		private System.Nullable<int> _pr_qtd;
		
		private EntitySet<ItemVenda> _itensVendas;
		
		private EntitySet<ItemVenda> _ItemVendas;
		
		private EntitySet<produtofornecedor> _produtofornecedors;
		
		private EntitySet<produtovenda> _produtovendas;
		
		private EntityRef<categoria> _categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpr_idChanging(int value);
    partial void Onpr_idChanged();
    partial void Onct_idChanging(int value);
    partial void Onct_idChanged();
    partial void Onpr_descricaoChanging(string value);
    partial void Onpr_descricaoChanged();
    partial void Onpr_unidadeChanging(string value);
    partial void Onpr_unidadeChanged();
    partial void Onpr_grifeChanging(string value);
    partial void Onpr_grifeChanged();
    partial void Onpr_valorChanging(decimal value);
    partial void Onpr_valorChanged();
    partial void Onpr_estoqueminimoChanging(int value);
    partial void Onpr_estoqueminimoChanged();
    partial void Onpr_categoriaChanging(string value);
    partial void Onpr_categoriaChanged();
    partial void Onpr_qtdChanging(System.Nullable<int> value);
    partial void Onpr_qtdChanged();
    #endregion
		
		public produto()
		{
			this._itensVendas = new EntitySet<ItemVenda>(new Action<ItemVenda>(this.attach_itensVendas), new Action<ItemVenda>(this.detach_itensVendas));
			this._ItemVendas = new EntitySet<ItemVenda>(new Action<ItemVenda>(this.attach_ItemVendas), new Action<ItemVenda>(this.detach_ItemVendas));
			this._produtofornecedors = new EntitySet<produtofornecedor>(new Action<produtofornecedor>(this.attach_produtofornecedors), new Action<produtofornecedor>(this.detach_produtofornecedors));
			this._produtovendas = new EntitySet<produtovenda>(new Action<produtovenda>(this.attach_produtovendas), new Action<produtovenda>(this.detach_produtovendas));
			this._categoria = default(EntityRef<categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pr_id
		{
			get
			{
				return this._pr_id;
			}
			set
			{
				if ((this._pr_id != value))
				{
					this.Onpr_idChanging(value);
					this.SendPropertyChanging();
					this._pr_id = value;
					this.SendPropertyChanged("pr_id");
					this.Onpr_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ct_id", DbType="Int NOT NULL")]
		public int ct_id
		{
			get
			{
				return this._ct_id;
			}
			set
			{
				if ((this._ct_id != value))
				{
					if (this._categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onct_idChanging(value);
					this.SendPropertyChanging();
					this._ct_id = value;
					this.SendPropertyChanged("ct_id");
					this.Onct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_descricao", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pr_descricao
		{
			get
			{
				return this._pr_descricao;
			}
			set
			{
				if ((this._pr_descricao != value))
				{
					this.Onpr_descricaoChanging(value);
					this.SendPropertyChanging();
					this._pr_descricao = value;
					this.SendPropertyChanged("pr_descricao");
					this.Onpr_descricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_unidade", DbType="VarChar(3)")]
		public string pr_unidade
		{
			get
			{
				return this._pr_unidade;
			}
			set
			{
				if ((this._pr_unidade != value))
				{
					this.Onpr_unidadeChanging(value);
					this.SendPropertyChanging();
					this._pr_unidade = value;
					this.SendPropertyChanged("pr_unidade");
					this.Onpr_unidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_grife", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string pr_grife
		{
			get
			{
				return this._pr_grife;
			}
			set
			{
				if ((this._pr_grife != value))
				{
					this.Onpr_grifeChanging(value);
					this.SendPropertyChanging();
					this._pr_grife = value;
					this.SendPropertyChanged("pr_grife");
					this.Onpr_grifeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_valor", DbType="Decimal(5,2) NOT NULL")]
		public decimal pr_valor
		{
			get
			{
				return this._pr_valor;
			}
			set
			{
				if ((this._pr_valor != value))
				{
					this.Onpr_valorChanging(value);
					this.SendPropertyChanging();
					this._pr_valor = value;
					this.SendPropertyChanged("pr_valor");
					this.Onpr_valorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_estoqueminimo", DbType="Int NOT NULL")]
		public int pr_estoqueminimo
		{
			get
			{
				return this._pr_estoqueminimo;
			}
			set
			{
				if ((this._pr_estoqueminimo != value))
				{
					this.Onpr_estoqueminimoChanging(value);
					this.SendPropertyChanging();
					this._pr_estoqueminimo = value;
					this.SendPropertyChanged("pr_estoqueminimo");
					this.Onpr_estoqueminimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_categoria", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pr_categoria
		{
			get
			{
				return this._pr_categoria;
			}
			set
			{
				if ((this._pr_categoria != value))
				{
					this.Onpr_categoriaChanging(value);
					this.SendPropertyChanging();
					this._pr_categoria = value;
					this.SendPropertyChanged("pr_categoria");
					this.Onpr_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_qtd", DbType="Int")]
		public System.Nullable<int> pr_qtd
		{
			get
			{
				return this._pr_qtd;
			}
			set
			{
				if ((this._pr_qtd != value))
				{
					this.Onpr_qtdChanging(value);
					this.SendPropertyChanging();
					this._pr_qtd = value;
					this.SendPropertyChanged("pr_qtd");
					this.Onpr_qtdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produto_itensVenda", Storage="_itensVendas", ThisKey="pr_id", OtherKey="CodigoProduto")]
		public EntitySet<ItemVenda> itensVendas
		{
			get
			{
				return this._itensVendas;
			}
			set
			{
				this._itensVendas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produto_itensVenda1", Storage="_ItemVendas", ThisKey="pr_id", OtherKey="CodigoProduto")]
		public EntitySet<ItemVenda> ItemVendas
		{
			get
			{
				return this._ItemVendas;
			}
			set
			{
				this._ItemVendas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produto_produtofornecedor", Storage="_produtofornecedors", ThisKey="pr_id", OtherKey="pr_id")]
		public EntitySet<produtofornecedor> produtofornecedors
		{
			get
			{
				return this._produtofornecedors;
			}
			set
			{
				this._produtofornecedors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produto_produtovenda", Storage="_produtovendas", ThisKey="pr_id", OtherKey="pr_id")]
		public EntitySet<produtovenda> produtovendas
		{
			get
			{
				return this._produtovendas;
			}
			set
			{
				this._produtovendas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_produto", Storage="_categoria", ThisKey="ct_id", OtherKey="ct_id", IsForeignKey=true)]
		public categoria categoria
		{
			get
			{
				return this._categoria.Entity;
			}
			set
			{
				categoria previousValue = this._categoria.Entity;
				if (((previousValue != value) 
							|| (this._categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._categoria.Entity = null;
						previousValue.produtos.Remove(this);
					}
					this._categoria.Entity = value;
					if ((value != null))
					{
						value.produtos.Add(this);
						this._ct_id = value.ct_id;
					}
					else
					{
						this._ct_id = default(int);
					}
					this.SendPropertyChanged("categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_itensVendas(ItemVenda entity)
		{
			this.SendPropertyChanging();
			entity.produto = this;
		}
		
		private void detach_itensVendas(ItemVenda entity)
		{
			this.SendPropertyChanging();
			entity.produto = null;
		}
		
		private void attach_ItemVendas(ItemVenda entity)
		{
			this.SendPropertyChanging();
			entity.produto1 = this;
		}
		
		private void detach_ItemVendas(ItemVenda entity)
		{
			this.SendPropertyChanging();
			entity.produto1 = null;
		}
		
		private void attach_produtofornecedors(produtofornecedor entity)
		{
			this.SendPropertyChanging();
			entity.produto = this;
		}
		
		private void detach_produtofornecedors(produtofornecedor entity)
		{
			this.SendPropertyChanging();
			entity.produto = null;
		}
		
		private void attach_produtovendas(produtovenda entity)
		{
			this.SendPropertyChanging();
			entity.produto = this;
		}
		
		private void detach_produtovendas(produtovenda entity)
		{
			this.SendPropertyChanging();
			entity.produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.produtofornecedor")]
	public partial class produtofornecedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pf_qtd;
		
		private string _pf_dtentrada;
		
		private int _pr_id;
		
		private int _fr_id;
		
		private string _pf_tipo;
		
		private string _pf_observacoes;
		
		private EntityRef<fornecedor> _fornecedor;
		
		private EntityRef<produto> _produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpf_qtdChanging(int value);
    partial void Onpf_qtdChanged();
    partial void Onpf_dtentradaChanging(string value);
    partial void Onpf_dtentradaChanged();
    partial void Onpr_idChanging(int value);
    partial void Onpr_idChanged();
    partial void Onfr_idChanging(int value);
    partial void Onfr_idChanged();
    partial void Onpf_tipoChanging(string value);
    partial void Onpf_tipoChanged();
    partial void Onpf_observacoesChanging(string value);
    partial void Onpf_observacoesChanged();
    #endregion
		
		public produtofornecedor()
		{
			this._fornecedor = default(EntityRef<fornecedor>);
			this._produto = default(EntityRef<produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pf_qtd", DbType="Int NOT NULL")]
		public int pf_qtd
		{
			get
			{
				return this._pf_qtd;
			}
			set
			{
				if ((this._pf_qtd != value))
				{
					this.Onpf_qtdChanging(value);
					this.SendPropertyChanging();
					this._pf_qtd = value;
					this.SendPropertyChanged("pf_qtd");
					this.Onpf_qtdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pf_dtentrada", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string pf_dtentrada
		{
			get
			{
				return this._pf_dtentrada;
			}
			set
			{
				if ((this._pf_dtentrada != value))
				{
					this.Onpf_dtentradaChanging(value);
					this.SendPropertyChanging();
					this._pf_dtentrada = value;
					this.SendPropertyChanged("pf_dtentrada");
					this.Onpf_dtentradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pr_id
		{
			get
			{
				return this._pr_id;
			}
			set
			{
				if ((this._pr_id != value))
				{
					if (this._produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpr_idChanging(value);
					this.SendPropertyChanging();
					this._pr_id = value;
					this.SendPropertyChanged("pr_id");
					this.Onpr_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fr_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int fr_id
		{
			get
			{
				return this._fr_id;
			}
			set
			{
				if ((this._fr_id != value))
				{
					if (this._fornecedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfr_idChanging(value);
					this.SendPropertyChanging();
					this._fr_id = value;
					this.SendPropertyChanged("fr_id");
					this.Onfr_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pf_tipo", DbType="VarChar(10)")]
		public string pf_tipo
		{
			get
			{
				return this._pf_tipo;
			}
			set
			{
				if ((this._pf_tipo != value))
				{
					this.Onpf_tipoChanging(value);
					this.SendPropertyChanging();
					this._pf_tipo = value;
					this.SendPropertyChanged("pf_tipo");
					this.Onpf_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pf_observacoes", DbType="VarChar(100)")]
		public string pf_observacoes
		{
			get
			{
				return this._pf_observacoes;
			}
			set
			{
				if ((this._pf_observacoes != value))
				{
					this.Onpf_observacoesChanging(value);
					this.SendPropertyChanging();
					this._pf_observacoes = value;
					this.SendPropertyChanged("pf_observacoes");
					this.Onpf_observacoesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fornecedor_produtofornecedor", Storage="_fornecedor", ThisKey="fr_id", OtherKey="fr_id", IsForeignKey=true)]
		public fornecedor fornecedor
		{
			get
			{
				return this._fornecedor.Entity;
			}
			set
			{
				fornecedor previousValue = this._fornecedor.Entity;
				if (((previousValue != value) 
							|| (this._fornecedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._fornecedor.Entity = null;
						previousValue.produtofornecedors.Remove(this);
					}
					this._fornecedor.Entity = value;
					if ((value != null))
					{
						value.produtofornecedors.Add(this);
						this._fr_id = value.fr_id;
					}
					else
					{
						this._fr_id = default(int);
					}
					this.SendPropertyChanged("fornecedor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produto_produtofornecedor", Storage="_produto", ThisKey="pr_id", OtherKey="pr_id", IsForeignKey=true)]
		public produto produto
		{
			get
			{
				return this._produto.Entity;
			}
			set
			{
				produto previousValue = this._produto.Entity;
				if (((previousValue != value) 
							|| (this._produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._produto.Entity = null;
						previousValue.produtofornecedors.Remove(this);
					}
					this._produto.Entity = value;
					if ((value != null))
					{
						value.produtofornecedors.Add(this);
						this._pr_id = value.pr_id;
					}
					else
					{
						this._pr_id = default(int);
					}
					this.SendPropertyChanged("produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produtovenda")]
	public partial class produtovenda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pv_dtsaida;
		
		private int _pv_qtd;
		
		private int _pr_id;
		
		private int _vn_id;
		
		private EntityRef<produto> _produto;
		
		private EntityRef<Venda> _Venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpv_dtsaidaChanging(string value);
    partial void Onpv_dtsaidaChanged();
    partial void Onpv_qtdChanging(int value);
    partial void Onpv_qtdChanged();
    partial void Onpr_idChanging(int value);
    partial void Onpr_idChanged();
    partial void Onvn_idChanging(int value);
    partial void Onvn_idChanged();
    #endregion
		
		public produtovenda()
		{
			this._produto = default(EntityRef<produto>);
			this._Venda = default(EntityRef<Venda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv_dtsaida", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string pv_dtsaida
		{
			get
			{
				return this._pv_dtsaida;
			}
			set
			{
				if ((this._pv_dtsaida != value))
				{
					this.Onpv_dtsaidaChanging(value);
					this.SendPropertyChanging();
					this._pv_dtsaida = value;
					this.SendPropertyChanged("pv_dtsaida");
					this.Onpv_dtsaidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv_qtd", DbType="Int NOT NULL")]
		public int pv_qtd
		{
			get
			{
				return this._pv_qtd;
			}
			set
			{
				if ((this._pv_qtd != value))
				{
					this.Onpv_qtdChanging(value);
					this.SendPropertyChanging();
					this._pv_qtd = value;
					this.SendPropertyChanged("pv_qtd");
					this.Onpv_qtdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pr_id
		{
			get
			{
				return this._pr_id;
			}
			set
			{
				if ((this._pr_id != value))
				{
					if (this._produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpr_idChanging(value);
					this.SendPropertyChanging();
					this._pr_id = value;
					this.SendPropertyChanged("pr_id");
					this.Onpr_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vn_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int vn_id
		{
			get
			{
				return this._vn_id;
			}
			set
			{
				if ((this._vn_id != value))
				{
					if (this._Venda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onvn_idChanging(value);
					this.SendPropertyChanging();
					this._vn_id = value;
					this.SendPropertyChanged("Vn_id");
					this.Onvn_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produto_produtovenda", Storage="_produto", ThisKey="pr_id", OtherKey="pr_id", IsForeignKey=true)]
		public produto produto
		{
			get
			{
				return this._produto.Entity;
			}
			set
			{
				produto previousValue = this._produto.Entity;
				if (((previousValue != value) 
							|| (this._produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._produto.Entity = null;
						previousValue.produtovendas.Remove(this);
					}
					this._produto.Entity = value;
					if ((value != null))
					{
						value.produtovendas.Add(this);
						this._pr_id = value.pr_id;
					}
					else
					{
						this._pr_id = default(int);
					}
					this.SendPropertyChanged("produto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="venda_produtovenda", Storage="_Venda", ThisKey="Vn_id", OtherKey="CodigoVenda", IsForeignKey=true)]
		public Venda Venda
		{
			get
			{
				return this._Venda.Entity;
			}
			set
			{
				Venda previousValue = this._Venda.Entity;
				if (((previousValue != value) 
							|| (this._Venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Venda.Entity = null;
						previousValue.produtovendas.Remove(this);
					}
					this._Venda.Entity = value;
					if ((value != null))
					{
						value.produtovendas.Add(this);
						this._vn_id = value.CodigoVenda;
					}
					else
					{
						this._vn_id = default(int);
					}
					this.SendPropertyChanged("Venda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Receita")]
	public partial class receita : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _rc_id;
		
		private int _cl_id;
		
		private string _rc_historico;
		
		private System.Nullable<decimal> _rc_lodesferico;
		
		private System.Nullable<decimal> _rc_loeesferico;
		
		private System.Nullable<decimal> _rc_podesferico;
		
		private System.Nullable<decimal> _rc_poeesferico;
		
		private System.Nullable<decimal> _rc_lodcilindrico;
		
		private System.Nullable<decimal> _rc_loecilindrico;
		
		private System.Nullable<decimal> _rc_podcilindrico;
		
		private System.Nullable<decimal> _rc_poecilindrico;
		
		private System.Nullable<decimal> _rc_lodeixo;
		
		private System.Nullable<decimal> _rc_loeeixo;
		
		private System.Nullable<decimal> _rc_podeixo;
		
		private System.Nullable<decimal> _rc_poeeixo;
		
		private System.Nullable<decimal> _rc_lodaltura;
		
		private System.Nullable<decimal> _rc_loealtura;
		
		private System.Nullable<decimal> _rc_podaltura;
		
		private System.Nullable<decimal> _rc_poealtura;
		
		private System.Nullable<decimal> _rc_loddnp;
		
		private System.Nullable<decimal> _rc_loednp;
		
		private System.Nullable<decimal> _rc_poddnp;
		
		private System.Nullable<decimal> _rc_poednp;
		
		private System.Nullable<decimal> _rc_adicao;
		
		private string _rc_nomemedico;
		
		private string _rc_observacoes;
		
		private System.DateTime _rc_data;
		
		private string _rc_dtavencimento;
		
		private EntityRef<cliente> _cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrc_idChanging(int value);
    partial void Onrc_idChanged();
    partial void Oncl_idChanging(int value);
    partial void Oncl_idChanged();
    partial void Onrc_historicoChanging(string value);
    partial void Onrc_historicoChanged();
    partial void Onrc_lodesfericoChanging(System.Nullable<decimal> value);
    partial void Onrc_lodesfericoChanged();
    partial void Onrc_loeesfericoChanging(System.Nullable<decimal> value);
    partial void Onrc_loeesfericoChanged();
    partial void Onrc_podesfericoChanging(System.Nullable<decimal> value);
    partial void Onrc_podesfericoChanged();
    partial void Onrc_poeesfericoChanging(System.Nullable<decimal> value);
    partial void Onrc_poeesfericoChanged();
    partial void Onrc_lodcilindricoChanging(System.Nullable<decimal> value);
    partial void Onrc_lodcilindricoChanged();
    partial void Onrc_loecilindricoChanging(System.Nullable<decimal> value);
    partial void Onrc_loecilindricoChanged();
    partial void Onrc_podcilindricoChanging(System.Nullable<decimal> value);
    partial void Onrc_podcilindricoChanged();
    partial void Onrc_poecilindricoChanging(System.Nullable<decimal> value);
    partial void Onrc_poecilindricoChanged();
    partial void Onrc_lodeixoChanging(System.Nullable<decimal> value);
    partial void Onrc_lodeixoChanged();
    partial void Onrc_loeeixoChanging(System.Nullable<decimal> value);
    partial void Onrc_loeeixoChanged();
    partial void Onrc_podeixoChanging(System.Nullable<decimal> value);
    partial void Onrc_podeixoChanged();
    partial void Onrc_poeeixoChanging(System.Nullable<decimal> value);
    partial void Onrc_poeeixoChanged();
    partial void Onrc_lodalturaChanging(System.Nullable<decimal> value);
    partial void Onrc_lodalturaChanged();
    partial void Onrc_loealturaChanging(System.Nullable<decimal> value);
    partial void Onrc_loealturaChanged();
    partial void Onrc_podalturaChanging(System.Nullable<decimal> value);
    partial void Onrc_podalturaChanged();
    partial void Onrc_poealturaChanging(System.Nullable<decimal> value);
    partial void Onrc_poealturaChanged();
    partial void Onrc_loddnpChanging(System.Nullable<decimal> value);
    partial void Onrc_loddnpChanged();
    partial void Onrc_loednpChanging(System.Nullable<decimal> value);
    partial void Onrc_loednpChanged();
    partial void Onrc_poddnpChanging(System.Nullable<decimal> value);
    partial void Onrc_poddnpChanged();
    partial void Onrc_poednpChanging(System.Nullable<decimal> value);
    partial void Onrc_poednpChanged();
    partial void Onrc_adicaoChanging(System.Nullable<decimal> value);
    partial void Onrc_adicaoChanged();
    partial void Onrc_nomemedicoChanging(string value);
    partial void Onrc_nomemedicoChanged();
    partial void Onrc_observacoesChanging(string value);
    partial void Onrc_observacoesChanged();
    partial void Onrc_dataChanging(System.DateTime value);
    partial void Onrc_dataChanged();
    partial void Onrc_dtavencimentoChanging(string value);
    partial void Onrc_dtavencimentoChanged();
    #endregion
		
		public receita()
		{
			this._cliente = default(EntityRef<cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int rc_id
		{
			get
			{
				return this._rc_id;
			}
			set
			{
				if ((this._rc_id != value))
				{
					this.Onrc_idChanging(value);
					this.SendPropertyChanging();
					this._rc_id = value;
					this.SendPropertyChanged("rc_id");
					this.Onrc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl_id", DbType="Int NOT NULL")]
		public int cl_id
		{
			get
			{
				return this._cl_id;
			}
			set
			{
				if ((this._cl_id != value))
				{
					if (this._cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncl_idChanging(value);
					this.SendPropertyChanging();
					this._cl_id = value;
					this.SendPropertyChanged("cl_id");
					this.Oncl_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_historico", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string rc_historico
		{
			get
			{
				return this._rc_historico;
			}
			set
			{
				if ((this._rc_historico != value))
				{
					this.Onrc_historicoChanging(value);
					this.SendPropertyChanging();
					this._rc_historico = value;
					this.SendPropertyChanged("rc_historico");
					this.Onrc_historicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_lodesferico", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_lodesferico
		{
			get
			{
				return this._rc_lodesferico;
			}
			set
			{
				if ((this._rc_lodesferico != value))
				{
					this.Onrc_lodesfericoChanging(value);
					this.SendPropertyChanging();
					this._rc_lodesferico = value;
					this.SendPropertyChanged("rc_lodesferico");
					this.Onrc_lodesfericoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_loeesferico", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_loeesferico
		{
			get
			{
				return this._rc_loeesferico;
			}
			set
			{
				if ((this._rc_loeesferico != value))
				{
					this.Onrc_loeesfericoChanging(value);
					this.SendPropertyChanging();
					this._rc_loeesferico = value;
					this.SendPropertyChanged("rc_loeesferico");
					this.Onrc_loeesfericoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_podesferico", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_podesferico
		{
			get
			{
				return this._rc_podesferico;
			}
			set
			{
				if ((this._rc_podesferico != value))
				{
					this.Onrc_podesfericoChanging(value);
					this.SendPropertyChanging();
					this._rc_podesferico = value;
					this.SendPropertyChanged("rc_podesferico");
					this.Onrc_podesfericoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_poeesferico", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_poeesferico
		{
			get
			{
				return this._rc_poeesferico;
			}
			set
			{
				if ((this._rc_poeesferico != value))
				{
					this.Onrc_poeesfericoChanging(value);
					this.SendPropertyChanging();
					this._rc_poeesferico = value;
					this.SendPropertyChanged("rc_poeesferico");
					this.Onrc_poeesfericoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_lodcilindrico", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_lodcilindrico
		{
			get
			{
				return this._rc_lodcilindrico;
			}
			set
			{
				if ((this._rc_lodcilindrico != value))
				{
					this.Onrc_lodcilindricoChanging(value);
					this.SendPropertyChanging();
					this._rc_lodcilindrico = value;
					this.SendPropertyChanged("rc_lodcilindrico");
					this.Onrc_lodcilindricoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_loecilindrico", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_loecilindrico
		{
			get
			{
				return this._rc_loecilindrico;
			}
			set
			{
				if ((this._rc_loecilindrico != value))
				{
					this.Onrc_loecilindricoChanging(value);
					this.SendPropertyChanging();
					this._rc_loecilindrico = value;
					this.SendPropertyChanged("rc_loecilindrico");
					this.Onrc_loecilindricoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_podcilindrico", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_podcilindrico
		{
			get
			{
				return this._rc_podcilindrico;
			}
			set
			{
				if ((this._rc_podcilindrico != value))
				{
					this.Onrc_podcilindricoChanging(value);
					this.SendPropertyChanging();
					this._rc_podcilindrico = value;
					this.SendPropertyChanged("rc_podcilindrico");
					this.Onrc_podcilindricoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_poecilindrico", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_poecilindrico
		{
			get
			{
				return this._rc_poecilindrico;
			}
			set
			{
				if ((this._rc_poecilindrico != value))
				{
					this.Onrc_poecilindricoChanging(value);
					this.SendPropertyChanging();
					this._rc_poecilindrico = value;
					this.SendPropertyChanged("rc_poecilindrico");
					this.Onrc_poecilindricoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_lodeixo", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_lodeixo
		{
			get
			{
				return this._rc_lodeixo;
			}
			set
			{
				if ((this._rc_lodeixo != value))
				{
					this.Onrc_lodeixoChanging(value);
					this.SendPropertyChanging();
					this._rc_lodeixo = value;
					this.SendPropertyChanged("rc_lodeixo");
					this.Onrc_lodeixoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_loeeixo", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_loeeixo
		{
			get
			{
				return this._rc_loeeixo;
			}
			set
			{
				if ((this._rc_loeeixo != value))
				{
					this.Onrc_loeeixoChanging(value);
					this.SendPropertyChanging();
					this._rc_loeeixo = value;
					this.SendPropertyChanged("rc_loeeixo");
					this.Onrc_loeeixoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_podeixo", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_podeixo
		{
			get
			{
				return this._rc_podeixo;
			}
			set
			{
				if ((this._rc_podeixo != value))
				{
					this.Onrc_podeixoChanging(value);
					this.SendPropertyChanging();
					this._rc_podeixo = value;
					this.SendPropertyChanged("rc_podeixo");
					this.Onrc_podeixoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_poeeixo", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_poeeixo
		{
			get
			{
				return this._rc_poeeixo;
			}
			set
			{
				if ((this._rc_poeeixo != value))
				{
					this.Onrc_poeeixoChanging(value);
					this.SendPropertyChanging();
					this._rc_poeeixo = value;
					this.SendPropertyChanged("rc_poeeixo");
					this.Onrc_poeeixoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_lodaltura", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_lodaltura
		{
			get
			{
				return this._rc_lodaltura;
			}
			set
			{
				if ((this._rc_lodaltura != value))
				{
					this.Onrc_lodalturaChanging(value);
					this.SendPropertyChanging();
					this._rc_lodaltura = value;
					this.SendPropertyChanged("rc_lodaltura");
					this.Onrc_lodalturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_loealtura", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_loealtura
		{
			get
			{
				return this._rc_loealtura;
			}
			set
			{
				if ((this._rc_loealtura != value))
				{
					this.Onrc_loealturaChanging(value);
					this.SendPropertyChanging();
					this._rc_loealtura = value;
					this.SendPropertyChanged("rc_loealtura");
					this.Onrc_loealturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_podaltura", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_podaltura
		{
			get
			{
				return this._rc_podaltura;
			}
			set
			{
				if ((this._rc_podaltura != value))
				{
					this.Onrc_podalturaChanging(value);
					this.SendPropertyChanging();
					this._rc_podaltura = value;
					this.SendPropertyChanged("rc_podaltura");
					this.Onrc_podalturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_poealtura", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_poealtura
		{
			get
			{
				return this._rc_poealtura;
			}
			set
			{
				if ((this._rc_poealtura != value))
				{
					this.Onrc_poealturaChanging(value);
					this.SendPropertyChanging();
					this._rc_poealtura = value;
					this.SendPropertyChanged("rc_poealtura");
					this.Onrc_poealturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_loddnp", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_loddnp
		{
			get
			{
				return this._rc_loddnp;
			}
			set
			{
				if ((this._rc_loddnp != value))
				{
					this.Onrc_loddnpChanging(value);
					this.SendPropertyChanging();
					this._rc_loddnp = value;
					this.SendPropertyChanged("rc_loddnp");
					this.Onrc_loddnpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_loednp", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_loednp
		{
			get
			{
				return this._rc_loednp;
			}
			set
			{
				if ((this._rc_loednp != value))
				{
					this.Onrc_loednpChanging(value);
					this.SendPropertyChanging();
					this._rc_loednp = value;
					this.SendPropertyChanged("rc_loednp");
					this.Onrc_loednpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_poddnp", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_poddnp
		{
			get
			{
				return this._rc_poddnp;
			}
			set
			{
				if ((this._rc_poddnp != value))
				{
					this.Onrc_poddnpChanging(value);
					this.SendPropertyChanging();
					this._rc_poddnp = value;
					this.SendPropertyChanged("rc_poddnp");
					this.Onrc_poddnpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_poednp", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_poednp
		{
			get
			{
				return this._rc_poednp;
			}
			set
			{
				if ((this._rc_poednp != value))
				{
					this.Onrc_poednpChanging(value);
					this.SendPropertyChanging();
					this._rc_poednp = value;
					this.SendPropertyChanged("rc_poednp");
					this.Onrc_poednpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_adicao", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> rc_adicao
		{
			get
			{
				return this._rc_adicao;
			}
			set
			{
				if ((this._rc_adicao != value))
				{
					this.Onrc_adicaoChanging(value);
					this.SendPropertyChanging();
					this._rc_adicao = value;
					this.SendPropertyChanged("rc_adicao");
					this.Onrc_adicaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_nomemedico", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string rc_nomemedico
		{
			get
			{
				return this._rc_nomemedico;
			}
			set
			{
				if ((this._rc_nomemedico != value))
				{
					this.Onrc_nomemedicoChanging(value);
					this.SendPropertyChanging();
					this._rc_nomemedico = value;
					this.SendPropertyChanged("rc_nomemedico");
					this.Onrc_nomemedicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_observacoes", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string rc_observacoes
		{
			get
			{
				return this._rc_observacoes;
			}
			set
			{
				if ((this._rc_observacoes != value))
				{
					this.Onrc_observacoesChanging(value);
					this.SendPropertyChanging();
					this._rc_observacoes = value;
					this.SendPropertyChanged("rc_observacoes");
					this.Onrc_observacoesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_data", DbType="Date NOT NULL")]
		public System.DateTime rc_data
		{
			get
			{
				return this._rc_data;
			}
			set
			{
				if ((this._rc_data != value))
				{
					this.Onrc_dataChanging(value);
					this.SendPropertyChanging();
					this._rc_data = value;
					this.SendPropertyChanged("rc_data");
					this.Onrc_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rc_dtavencimento", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string rc_dtavencimento
		{
			get
			{
				return this._rc_dtavencimento;
			}
			set
			{
				if ((this._rc_dtavencimento != value))
				{
					this.Onrc_dtavencimentoChanging(value);
					this.SendPropertyChanging();
					this._rc_dtavencimento = value;
					this.SendPropertyChanged("rc_dtavencimento");
					this.Onrc_dtavencimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_receita", Storage="_cliente", ThisKey="cl_id", OtherKey="cl_id", IsForeignKey=true)]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.receitas.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.receitas.Add(this);
						this._cl_id = value.cl_id;
					}
					else
					{
						this._cl_id = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
